framework:
    cache:
        app: cache.adapter.filesystem
        system: cache.adapter.system
        directory: '%kernel.cache_dir%/pools'

when@prod:
    framework:
        cache:
            app: cache.adapter.apcu
